name: CI/CD on FE

on:
 push:
  branches: [master]
 pull_request:
  branches: []
  
jobs:
 docker:
  name: Docker Build and Push
  runs-on: ubuntu-latest
  steps:
   - name: checkout
     uses: actions/checkout@v3

   - name: Login to Docker Hub
     uses: docker/login-action@v3
     with:
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      password: ${{ secrets.DOCKER_HUB_PASSWORD}} 
   - name: Set Up Docker Buildx
     uses: docker/setup-buildx-action@v3

   - name: Build and Push Generat-Election-FE
     uses: docker/build-push-action@v6
     with:
      context: ../../Generat-Election-FE
      file: ../../Generat-Election-FE/Dockerfile
      push: true
      tags: ${{ secrets.DOCKER_HUB_USERNAME }}/Generat-Election-FE:latest 



