name: CI/CD On BE

on:
 push:
  branches: [master]
 pull_request:
  branches: []

jobs:
 docker-build:
  name: Docker Build and Push
  runs-on: ubuntu-latest
  steps:
   - name: checkout
     uses: actions/checkout@v3

   - name: docker build
     run: docker build -t general-election-be:${{ github.sha }} general-election-be

 test-docker-image:
  name: Test Docker Image
  runs-on: ubuntu-latest
  needs: docker-build
  steps:
    - name: run tests
      run: docker run general-election-be:${{ github.sha }} npm test

 deploy-docker-image:
  name: Deploy Docker Image
  runs-on: ubuntu-latest
  needs: test-docker-image
  steps:
    - name: login to docker hub
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: push Docker image
      run: |
       docker tag generat-election-fe:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/general-election-be:${{ github.sha }}
       docker push ${{ secrets.DOCKER_HUB_USERNAME }}/general-election-be:${{ github.sha }}

 docker:
  name: Docker Build and Push
  runs-on: ubuntu-latest
  steps:
   - name: checkout
     uses: actions/checkout@v3

   - name: Login to Docker Hub
     uses: docker/login-action@v3
     with:
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      password: ${{ secrets.DOCKER_HUB_PASSWORD }}
   - name: Set Up Docker Buildx
     uses: docker/setup-buildx-action@v3

   - name: Build and Push general-election-be
     uses: docker/build-push-action@v6
     with:
      context: general-election-be
      file: ./general-election-be/Dockerfile
      push: true
      tags: ${{ secrets.DOCKER_HUB_USERNAME }}/general-election-be:latest


 aws:
  name: AWS ECR
  runs-on: ubuntu-latest
  needs: docker
  steps:
   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v3
     with:
      role-to-assume: arn:aws:iam::${{ secrets.ACCESS_KEY_ID}}:role/general-election-be
      aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      aws-region: ${{secrets.ACCESS_KEY_ID}}

   - name: Login to AWS ECR
     id: login-ecr
     uses: aws-actions/amazon-ecr-login@v2    
   
   - name: Build, tag, and push image to AWS ECR
     id: build-image
     env:
      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      ECR_REPOSITORY: general-election-be
      IMAGE_TAG: ${{ github.sha }}
     run: |
      docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG general-election-be
      docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


